2017/10/30 11:02:23 [crit] 15813#0: *9 connect() to unix:///home/lsg/workspace/django/mysite/nginx.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/lsg/workspace/django/mysite/nginx.sock:", host: "127.0.0.1"
2017/10/30 11:02:25 [crit] 15813#0: *9 connect() to unix:///home/lsg/workspace/django/mysite/nginx.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/lsg/workspace/django/mysite/nginx.sock:", host: "127.0.0.1"
2017/10/30 11:02:34 [crit] 15813#0: *9 connect() to unix:///home/lsg/workspace/django/mysite/nginx.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/lsg/workspace/django/mysite/nginx.sock:", host: "127.0.0.1"
2017/10/30 11:02:40 [crit] 15813#0: *13 connect() to unix:///home/lsg/workspace/django/mysite/nginx.sock failed (2: No such file or directory) while connecting to upstream, client: 192.168.1.101, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/lsg/workspace/django/mysite/nginx.sock:", host: "192.168.1.101"
2017/10/30 11:02:40 [crit] 15813#0: *13 connect() to unix:///home/lsg/workspace/django/mysite/nginx.sock failed (2: No such file or directory) while connecting to upstream, client: 192.168.1.101, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///home/lsg/workspace/django/mysite/nginx.sock:", host: "192.168.1.101"
2017/10/30 11:04:59 [crit] 15813#0: *16 connect() to unix:///home/lsg/workspace/django/mysite/nginx.sock failed (2: No such file or directory) while connecting to upstream, client: 192.168.1.101, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/lsg/workspace/django/mysite/nginx.sock:", host: "192.168.1.101"
2017/10/30 11:05:13 [crit] 15813#0: *18 connect() to unix:///home/lsg/workspace/django/mysite/nginx.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/lsg/workspace/django/mysite/nginx.sock:", host: "127.0.0.1"
2017/10/30 11:08:41 [crit] 1823#0: *1 connect() to unix:///home/lsg/workspace/django/mysite/nginx.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/lsg/workspace/django/mysite/nginx.sock:", host: "127.0.0.1"
2017/10/30 11:08:42 [crit] 1823#0: *1 connect() to unix:///home/lsg/workspace/django/mysite/nginx.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/lsg/workspace/django/mysite/nginx.sock:", host: "127.0.0.1"
2017/10/30 11:08:43 [crit] 1823#0: *1 connect() to unix:///home/lsg/workspace/django/mysite/nginx.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/lsg/workspace/django/mysite/nginx.sock:", host: "127.0.0.1"
2017/10/30 11:09:25 [crit] 1823#0: *1 connect() to unix:///home/lsg/workspace/django/mysite/nginx.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/lsg/workspace/django/mysite/nginx.sock:", host: "127.0.0.1"
2017/10/30 11:13:24 [crit] 1823#0: *6 connect() to unix:///home/lsg/workspace/django/mysite/nginx.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/lsg/workspace/django/mysite/nginx.sock:", host: "127.0.0.1"
2017/10/30 11:50:56 [error] 31583#0: *35 connect() to unix:///home/lsg/workspace/django/mysite/nginx.sock failed (111: Connection refused) while connecting to upstream, client: 192.168.1.101, server: localhost, request: "GET /user/1/ HTTP/1.1", upstream: "uwsgi://unix:///home/lsg/workspace/django/mysite/nginx.sock:", host: "192.168.1.101"
2017/10/30 11:51:11 [error] 31583#0: *35 connect() to unix:///home/lsg/workspace/django/mysite/nginx.sock failed (111: Connection refused) while connecting to upstream, client: 192.168.1.101, server: localhost, request: "GET /user/1/ HTTP/1.1", upstream: "uwsgi://unix:///home/lsg/workspace/django/mysite/nginx.sock:", host: "192.168.1.101"
2017/10/30 11:51:21 [error] 31583#0: *42 connect() to unix:///home/lsg/workspace/django/mysite/nginx.sock failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /user/1/ HTTP/1.1", upstream: "uwsgi://unix:///home/lsg/workspace/django/mysite/nginx.sock:", host: "127.0.0.1"
